version: '2'

services:
  forge:
    image: mc-forge-server-1.7.10
    build: .
    ports:
      - "25565:25565"
    volumes:
      - ./volumes/mods:/minecraft/mods
      - ./volumes/config:/minecraft/config
      - ./volumes/banned-ips.json:/minecraft/banned-ips.json
      - ./volumes/baned-players.json:/minecraft/banned-players.json
      - ./volumes/ops.json:/minecraft/ops.json
      - ./volumes/server.properties:/minecraft/server.properties
      - ./volumes/whitelist.json:/minecraft/whitelist.json
      - ./volumes/world:/minecraft/world