version: '3'

services:
  forge:
    image: mc-forge-server-1.12.2
    build: .
    ports:
      - "25565:25565"
    environment:
      - MINECRAFT_VERSION=1.12.2
      - FORGE_VERSION=1.12.2-14.23.5.2836
    volumes:
      - ./volumes/mods:/minecraft/mods
      - ./volumes/config:/minecraft/config
      - ./volumes/banned-ips.json:/minecraft/banned-ips.json
      - ./volumes/banned-players.json:/minecraft/banned-players.json
      - ./volumes/ops.json:/minecraft/ops.json
      - ./volumes/server.properties:/minecraft/server.properties
      - ./volumes/whitelist.json:/minecraft/whitelist.json
      - ./volumes/world:/minecraft/world